development:
  host: localhost
  database: optionplus_development

test:
  host: localhost
  database: optionplus_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
 
